import streamlit as st
import datetime
import os

from agent.agent_workflow import GraphBuilder

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("AI TRAVEL PLANNER AGENT")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I help you in planning a trip? Let me know where do you want to visit.")


# Build the graph once and cache it across reruns/sessions
@st.cache_resource
def get_graph():
    graph_builder = GraphBuilder(model_provider="groq")
    return graph_builder()  # __call__ -> build_graph()


react_app = get_graph()

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="E.G plan a trip for goa in 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Bot is Loading....."):
            messages = {"messages": [user_input]}
            output = react_app.invoke(messages)

            if isinstance(output, dict) and "messages" in output:
                answer = output["messages"][-1].content
            else:
                answer = str(output)

        markdown_content = f"""# AI Travel Plan
**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
**Created by:** Atriyo's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*"""
        st.markdown(markdown_content)

    except Exception as e:
        st.error(f"The response failed due to {e}")